ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [
            com.irozumi.ApplicationKt.module
        ]
    }
}

irozumi {
    database {
        url = "jdbc:postgresql://localhost:5432/IroZumi"
        url = ${?DATABASE_URL}
        user = "postgres"
        user = ${?DATABASE_USER}
        password = "gomaru"
        password = ${?DATABASE_PASSWORD}
        maximumPoolSize = 10
    }

    jwt {
        secret = "irozumi-secret-key-change-in-production-2026-32chars!!"
        secret = ${?JWT_SECRET}
        issuer = "irozumi"
        audience = "irozumi-app"
        accessTokenExpirationMs = 900000
        refreshTokenExpirationMs = 2592000000
    }
}

cloudinary {
    cloudName = "dyoojjr6u"
    cloudName = ${?CLOUDINARY_CLOUD_NAME}
    apiKey = "238573233435571"
    apiKey = ${?CLOUDINARY_API_KEY}
    apiSecret = "YBP4bQJuvJJRNqwA7vmH67nWiJE"
    apiSecret = ${?CLOUDINARY_API_SECRET}
}